import React from 'react';
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <h1>Welcome to wild-mongoose-dash</h1>
        <p>This app was generated by Applaa</p>
        <p>🚀 Successfully deployed to Vercel!</p>
      </header>
    </div>
  );
}

export default App;